# Generated by Django 4.2.7 on 2023-12-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('create_at', models.DateField(verbose_name='Дата создания')),
                ('is_publication', models.BooleanField()),
                ('views_count', models.IntegerField(verbose_name='Счётчик просмотров')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100, verbose_name='Название категории'),
        ),
    ]
